Update LeisureMeta mapping and contract address
maticnetwork/polygon-token-list pull request #596
Opened 2024-04-03 08:28 UTC by tong92

2024-04-17 06:49 UTC, Groovytent requested changes
Please update you token details on polygonscan by contacting polygonscan support team(https://polygonscan.com/contactus) and also share the logo URL in svg format.

2024-05-02 01:07 UTC, yougonow commented
The token information on polygonscan has updated. you can check here. (https://polygonscan.com/address/0xb2d3edf61b27ab28288d8c760fa686be084ff526)

2024-06-19 07:48 UTC, Groovytent approved these changes
LGTM

2024-06-20 01:37 UTC, tong92 commented
update all commit signing with force push

2025-04-14 08:33 UTC, closed without merging